# Generated by Django 5.0.1 on 2025-10-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plancoverage',
            name='unique_coverage_per_plan',
        ),
        migrations.AlterUniqueTogether(
            name='plancoverage',
            unique_together={('plan', 'coverage_type')},
        ),
    ]
