# Generated by Django 5.0.1 on 2025-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_plancoverage_unique_coverage_per_plan_and_more'),
        ('users', '0003_alter_person_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceregistration',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='insurance_registrations', to='users.person', verbose_name='افراد تحت پوشش'),
        ),
    ]
