# Generated by Django 5.0.1 on 2025-10-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='city',
            name='unique_city_per_state',
        ),
        migrations.RemoveConstraint(
            model_name='county',
            name='unique_county_per_city',
        ),
        migrations.RemoveConstraint(
            model_name='district',
            name='unique_district_per_region',
        ),
        migrations.RemoveConstraint(
            model_name='region',
            name='unique_region_per_county',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('city', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('county', 'code')},
        ),
    ]
