# Generated by Django 5.0.1 on 2025-10-06 11:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(help_text='کد ملی 10 رقمی', max_length=10, verbose_name='کد ملی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('relation', models.CharField(choices=[('self', 'خود'), ('spouse', 'همسر'), ('child', 'فرزند'), ('parent', 'والدین'), ('sibling', 'خواهر/برادر'), ('other', 'سایر')], max_length=20, verbose_name='نسبت با بیمه\u200cگذار')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
                'db_table': 'persons',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'national_code')},
            },
        ),
    ]
