# Generated by Django 5.0.1 on 2025-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(choices=[('spouse', 'همسر'), ('child', 'فرزند'), ('parent', 'والدین'), ('sibling', 'خواهر/برادر'), ('other', 'سایر')], max_length=20, verbose_name='نسبت با بیمه\u200cگذار'),
        ),
    ]
