# Generated by Django 5.0.1 on 2025-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_document'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='user_docume_user_id_16802b_idx',
            old_name='user_docume_user_id_b8a9f5_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='user_docume_registr_2e711b_idx',
            old_name='user_docume_registr_c7e8d4_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='user_docume_is_veri_41781f_idx',
            old_name='user_docume_is_veri_a3f2e1_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
    ]
